###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Nvidia",
  "symbol": "NVDA",
  "price": 700,
  "image": "NVDA.png"
}

###

@assetId = {{createAsset.response.body._id}}
###

GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/AMZN

###
# @name createWallet
POST http://localhost:3000/wallet
###

@walletId = {{createWallet.response.body._id}}
GET http://localhost:3000/wallet
###

GET http://localhost:3000/wallet/{{walletId}}

###
# @name createWallet
###
POST http://localhost:3000/wallet/{{walletId}}/assets
Content-Type: application/json

{
  "assetId" : "{{assetId}}",
  "shares": 8170
}

### 
POST http://localhost:3000/orders
Content-Type: application/json

{
  "walletId": "13b7beeb-351d-4664-bf35-8449828a583d",
  "assetId": "a96e7096-b37f-4b6d-9a42-3b6b53233ae2",
  "shares": 200,
  "price": 1500,
  "type": "BUY"
}



###
GET http://localhost:3000/orders?walletId=13b7beeb-351d-4664-bf35-8449828a583d